// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrmtewLiVOVmsp7-u1bZwdX4AC0DY6zdU',
    appId: '1:868266579548:web:8aac05d628367e59c13899',
    messagingSenderId: '868266579548',
    projectId: 'gawa-8e84a',
    authDomain: 'gawa-8e84a.firebaseapp.com',
    storageBucket: 'gawa-8e84a.firebasestorage.app',
    measurementId: 'G-GTQ4QFFR77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ5KHPQ3Jye-tzeBJdsweB7netWalJTfQ',
    appId: '1:868266579548:android:0b6c75375c3153cac13899',
    messagingSenderId: '868266579548',
    projectId: 'gawa-8e84a',
    storageBucket: 'gawa-8e84a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW221yB8z9V0QjpT7jmif8jhSZYRDv_xw',
    appId: '1:868266579548:ios:e0018ced2ad6430ac13899',
    messagingSenderId: '868266579548',
    projectId: 'gawa-8e84a',
    storageBucket: 'gawa-8e84a.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW221yB8z9V0QjpT7jmif8jhSZYRDv_xw',
    appId: '1:868266579548:ios:e0018ced2ad6430ac13899',
    messagingSenderId: '868266579548',
    projectId: 'gawa-8e84a',
    storageBucket: 'gawa-8e84a.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrmtewLiVOVmsp7-u1bZwdX4AC0DY6zdU',
    appId: '1:868266579548:web:7c0d517aada4a36bc13899',
    messagingSenderId: '868266579548',
    projectId: 'gawa-8e84a',
    authDomain: 'gawa-8e84a.firebaseapp.com',
    storageBucket: 'gawa-8e84a.firebasestorage.app',
    measurementId: 'G-CS4E2WFW88',
  );
}
